SELECT ANIMAL_ID, NAME
FROM(
SELECT I.ANIMAL_ID, I.NAME 
FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O ON
    I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY O.DATETIME-I.DATETIME DESC)
WHERE ROWNUM <= 2

--출처: 프로그래머스 코딩 테스트 연습
--https://school.programmers.co.kr/learn/challenges